apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: aprs-tracker
  name: aprs-tracker
  namespace: wp-lorawan
spec:
  maxReplicas: 4
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: DeploymentConfig
    name: aprs-tracker
  targetCPUUtilizationPercentage: 80
