apiVersion: v1
kind: Service
metadata:
  labels:
    app: aprs-tracker
  name: aprs-tracker
  namespace: wp-lorawan
spec:
  ports:
  - name: 3000-tcp
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: aprs-tracker
    deploymentconfig: aprs-tracker
  sessionAffinity: None
  type: ClusterIP
