apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: redis-persistent
  name: redis-persistent
  namespace: wp-lorawan
spec:
  replicas: 1
  selector:
    app: redis-persistent
    deploymentconfig: redis-persistent
  strategy:
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: redis-persistent
        deploymentconfig: redis-persistent
    spec:
      containers:
      - image: wp-lorawan/redis-persistent:latest
        imagePullPolicy: Always
        name: redis-persistent
        ports:
        - containerPort: 6379
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 250m
            memory: 250Mi
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /redis
          name: redis-data
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3 
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis-data
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - redis-persistent
      from:
        kind: ImageStreamTag
        name: redis-persistent:latest
        namespace: wp-lorawan
    type: ImageChange
