apiVersion: v1
kind: Pod
metadata:
  generateName: dns-injector-1-
  labels:
    app: dns-injector
spec:
  containers:
    -
      name: dns-injector
      image: '172.30.220.59:5000/weepee-registry/dns-injector'
      ports:
      env:
        -
          name: OPENSHIFT_NAMESPACE
          value: wp-lorawan
      resources:
        limits:
          cpu: 150m
          memory: 256Mi
        requests:
          cpu: 50m
          memory: 50Mi
      terminationMessagePath: /dev/termination-log
      imagePullPolicy: Always
  restartPolicy: Never
  terminationGracePeriodSeconds: 30
  dnsPolicy: ClusterFirst
