---
securityheaders-openshift:
  Access-Control-Allow-Headers: 'Content-Type, X-CSRF-Token'
  Access-Control-Allow-Methods: 'GET, OPTIONS, POST, DELETE, PUT'
  Access-Control-Allow-Origin: '*'
  Access-Control-Max-Age: 1728000
  Content-Security-Policy: "default-src https: data: 'unsafe-inline' 'unsafe-eval'"
  Strict-Transport-Security: max-age=31536000; includeSubDomains
  X-Content-Type-Options: nosniff
  X-Frame-Options: SAMEORIGIN
  X-Xss-Protection: 1; mode=block
securityheaders-development:
  Access-Control-Allow-Headers: 'Content-Type, X-CSRF-Token'
  Access-Control-Allow-Methods: 'GET, OPTIONS, POST, DELETE, PUT'
  Access-Control-Allow-Origin: '*'
  Access-Control-Max-Age: 1728000
  Content-Security-Policy: "default-src http: data: 'unsafe-inline' 'unsafe-eval'"
  Strict-Transport-Security: max-age=31536000; includeSubDomains
  X-Content-Type-Options: nosniff
  X-Frame-Options: SAMEORIGIN
  X-Xss-Protection: 1; mode=block
tokens:
  9c79b9f35373488e6713273298880587: thethingsnetwork
  0dd718f091da5a2f2d6884761b84ffbd: wirelessthings
debug: false
# if not found keep one month
expire-error: 2592000
# if found keep 90 dagen
expire-valid: 7776000
sentry:
  dsn: https://95e490863303484fb9b6b52896f49164:b38b1640bfcd44ad93806a91f3c8e16e@sentry.io/123269
environment: openshift
openshift:
  namespace: wp-lorawan
appsecret: 'alo alo this is ure calling for a very secret message to tell you ... sst'
# type: car|van|pickup
# pass create via https://apps.magicbug.co.uk/passcode/
lora:
  wirelessthings_be:
      260115E4:
        password: 16563
        callsign: ON3ZOE
        type: walk
  thethingsnetwork_org:
    0045B87AC06F742B:
        password: 16563
        callsign: ON3ZOE-1
        type: walk
