apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: letsencrypt
  name: letsencrypt
spec:
  output:
    to:
      kind: ImageStreamTag
      name: letsencrypt:latest
  source:
    git:
      ref: master
      uri: git@github.com:weepee-org/wp-lorawan.git
    contextDir: letsencrypt/
    type: Git
    sourceSecret:
      name:  wp-lorawan
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: letsencrypt-injector:latest
        namespace: wp-alpha-registry
    type: Docker
  triggers:
  - type: ConfigChange
